# Automatização de uma busca no site Google utilizando Site_Prism

source 'https://rubygems.org'

gem 'capybara', '2.14.4'
gem 'cucumber', '~> 3.0', '>= 3.0.1'
gem 'selenium-webdriver', '3.4.4'
gem 'site_prism'
