# Automatização de uma busca no site Google utilizando o metodo Page Object

source "https://rubygems.org"

gem "cucumber", '2.4.0'
gem "capybara", '2.14.4'
gem "selenium-webdriver", '3.4.4'
gem "chromedriver-helper", '1.1.0'﻿

